GET  http://localhost:5000/feedback/


###

POST http://localhost:5000/feedback/
Content-Type: application/json

{
    "userid": "e21682f9-9ffc-4227-b4d6-ae7b41519f02",
    "title": "loi phan mem332q",
    "content": "loi phan mem loi xay ra thuong xuyen33kk11",
    "createdat": ""
}