GET  http://localhost:5000/feedback/


###

POST http://localhost:5000/feedback/
Content-Type: application/json

{
    "userid": "22200000-0000-474c-b092-b0dd880c07e2",
    "title": "loi phan mem332q2",
    "content": "loi phan mem loi xay ra thuong xuyen33kk11",
    "createdat": ""
}
###
PUT http://localhost:5000/feedback/
Content-Type: application/json

{
    "id": "10"
}